### ISSUE TITLE
CAP con 2 o 4 cifre

### ISSUE THREAD

**Issue by mgrassotti** [MatteoHenryChinaski/Comuni-Italiani-2018-Sql-Json-excel#1]
Salve,

ho notato che in https://github.com/MatteoHenryChinaski/Comuni-Italiani-2018-Sql-Json-excel/blob/master/italy_cap.json ci sono dei cap con 2 o 4 cifre. 
E' voluto? Sono cap della zona di Roma senzi gli 0 iniziali?

Grazie mille

**Comment by MatteoHenryChinaski** [comment]
Ho controllato il file json americane sembrano tutti di 5 zeri. Credo non
esistono numeri cap inferiori o superiori di 5 cifre, se ci sono è perché è
un errore oppure è una situazione anomala

Il ven 26 ott 2018, 12:57 Matteo Grassotti <notifications@github.com> ha
scritto:

**Comment by mgrassotti** [comment]
Intendevo cap come questi:
https://github.com/MatteoHenryChinaski/Comuni-Italiani-2018-Sql-Json-excel/blob/master/italy_cap.json#L18896

**Comment by MatteoHenryChinaski** [comment]
il bookmarl che hai messo nel link non funziona perché non è un file html
ed è il file è molto grande. copia e incolla la porzione dei cap che non ti
convincono.

Il giorno ven 26 ott 2018 alle ore 14:52 Matteo Grassotti <
notifications@github.com> ha scritto:

**Comment by mgrassotti** [comment]
```
        {
		"istat": "58023",
		"cap": "24"
	},
	{
		"istat": "58024",
		"cap": "60"
	},
	{
		"istat": "58025",
		"cap": "30"
	},
```
```
        {
		"istat": "57010",
		"cap": "2040"
	},
	{
		"istat": "57011",
		"cap": "2030"
	},
	{
		"istat": "57012",
		"cap": "2041"
	},
```
anche gli ultimi 2 sembrano un po' strani:
```
        {
		"istat": "Total",
		"cap": "7978"
	},
	{
		"istat": ""
	}
```
Grazie

**Comment by MatteoHenryChinaski** [comment]
Ok ho capito... Non so risponderti prova a vedere le relazioni del database
(che installi tramite il file .sql) e scoprì a quali comuni appartengono
quei cap. Magari sono comuni dismessi.

Il ven 26 ott 2018, 22:35 Matteo Grassotti <notifications@github.com> ha
scritto:

**Comment by mgrassotti** [comment]
Ma guarda, ho pensato di segnalare la cosa per contribuire. 
Vedi tu se vuoi indagare oltre. 
Ciao
