### ISSUE TITLE
aggiornato or not?

### ISSUE THREAD

**Issue by paskuale75** [MatteoHenryChinaski/Comuni-Italiani-2018-Sql-Json-excel#3]
Ciao, molto interessante questo repo, che tipo di affidabilità ha ad ogg (maggio 2020) ?
Grazie

**Comment by MatteoHenryChinaski** [comment]
se dalla data del report ad oggi non ci sono state modifiche importante
sulle province, il report è affidabile.
Riguardo i comuni ogni anni c'è qualche "unioni di comuni" cioè prima erano
3 o 4 comuni (sempre geograficamente vicini) e poi la provincia decide di
unificarli cancellandoli tutti e creandone uno nuovo

Il giorno lun 18 mag 2020 alle ore 15:04 pasquale <notifications@github.com>
ha scritto:

**Comment by paskuale75** [comment]
grazie @MatteoHenryChinaski già che siamo in argomento, da dove si evince se vengono fatte "unioni di comuni" nel tempo ?

**Comment by MatteoHenryChinaski** [comment]
questo è abbastanza affidabile https://www.tuttitalia.it/variazioni-amministrative/nuovi-comuni-2020/

**Comment by paskuale75** [comment]
grazie per l'ottimo lavoro

**Comment by MatteoHenryChinaski** [comment]
Sì evince da quel sito sopra elencato e dai siti istituzionali, tipo camera
e istat

Il mer 20 mag 2020, 08:46 pasquale <notifications@github.com> ha scritto:
